"""Adiciona file_url e file_type à tabela message

Revision ID: 0d9af4c53b7f
Revises: 1071900bc575
Create Date: 2025-02-13 21:09:48.694970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9af4c53b7f'
down_revision = '1071900bc575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
