"""Adiciona file_url e file_type à tabela message

Revision ID: 1936b122c8d3
Revises: 0d9af4c53b7f
Create Date: 2025-02-13 21:29:14.322006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1936b122c8d3'
down_revision = '0d9af4c53b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('msg',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('msg',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
