"""adiciona_coluna_room_id_na_tabela_message

Revision ID: e668a21835e4
Revises: 1936b122c8d3
Create Date: 2025-08-11 17:12:23.669867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e668a21835e4'
down_revision = '1936b122c8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_message_room_id', 'room', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_room_id', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
